Home page content b
Recoded-Spark-Turkey-2022/RE-Minded pull request #21
Opened 2022-12-29 17:05 UTC by MenarSelamet

-Layout made
-Responsive
-Tests will be done after all the components of the home page are done
-Every branch is responsible of it's own component, please don't look at the merged componentes above or beneath, they're for testing purposes. This branch is for component B only which is they yellow section :D

2022-12-29 18:28 UTC, symys commented on tailwind.config.js
>  };
need importing for poppins font
@import url("https://fonts.googleapis.com/css2?family=Poppins&display=swap");
:)))

2022-12-29 18:29 UTC, symys requested changes
well done, I can't wait merge this ♥

2022-12-29 20:17 UTC, SohailMahmoud approved these changes
Ready to be merged, well done

2022-12-30 06:11 UTC, symys approved these changes
well done!

2022-12-30 06:12 UTC, merged