12 careers page
Recoded-Spark-Turkey-2022/RE-Minded pull request #27
Opened 2022-12-31 10:33 UTC by symys

Completed careers page with responsive design
Added snapshot test

2022-12-31 13:01 UTC, MenarSelamet commented on src/ComponentFolders/CareersPage/CareersPageMain.jsx
> +        <div className='bg-yellow-300 w-full'>
Great job, can you just changes the background color to "bg-amber-200" to suit the rest of the site 💯

2022-12-31 13:01 UTC, MenarSelamet requested changes
Thankkk youuu for your beautiful worrrrkk, just a background color change and we're done :D

2023-01-02 08:20 UTC, symys commented
> Thankkk youuu for your beautiful worrrrkk, just a background color change and we're done :D

thank youuu so much ! 🤗 I changed the color 🎨

2023-01-04 12:02 UTC, MenarSelamet approved these changes

2023-01-05 07:09 UTC, SohailMahmoud approved these changes

2023-01-05 07:18 UTC, merged