30 therapist create page
Recoded-Spark-Turkey-2022/RE-Minded pull request #33
Opened 2023-01-02 08:11 UTC by symys

Completed page without Link
Added responsiveness
Added snaphot test without link to thank you page

2023-01-02 09:19 UTC, MenarSelamet approved these changes

2023-01-04 07:09 UTC, SohailMahmoud requested changes
Amazing works with the responsiveness and the styling, keep it up

2023-01-04 07:09 UTC, SohailMahmoud commented on src/ComponentFolders/TherapistCreatePage/TherapistCreatePage.jsx
> +      <form className="mb-0 mt-4 space-y-6" action="#" method="POST">
We are not using any HTML form requests, so there is no need to write any actions or methods

2023-01-04 07:09 UTC, SohailMahmoud commented on tailwind.config.js
> +        xl: '1280px',
Gerek yok for the xl :D

2023-01-04 11:42 UTC, SohailMahmoud approved these changes

2023-01-04 12:04 UTC, merged